apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-deployment
  labels:
    app: demo-api
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
  labels:
    app: demo-api
  namespace: production
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: demo-api
  type: ClusterIP
---