apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-build-image
  namespace: tekton-pipelines
spec:
  resources:
    - name: docker-source
      type: git
    - name: builtImage
      type: image
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
    - name: pathToContext
      type: string
      description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
  tasks:
  - name: source-to-image
    taskRef:
      name: task-build-docker-image
    params:
      - name: pathToDockerFile
        value: "$(params.pathToDockerFile)"
    resources:
        inputs:
          - name: docker-source
            resource: docker-source
        outputs:
          - name: builtImage
            resource: builtImage