apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-deploy-using-kubectl
  namespace: tekton-pipelines
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
  tasks:
  - name: deploy-to-cluster
    taskRef:
      name: deploy-using-kubectl
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.imageTag)"
    resources:
      inputs:
        - name: git-source
          resource: git-source