apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
  namespace: tekton-pipelines
secrets:
  - name: dockercreds
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
  namespace: tekton-pipelines
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: pipeline-account
  namespace: tekton-pipelines
---