apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-svc-account
secrets:
- name: dockercreds

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: test-svc-account
  namespace: default