apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: demo-api-tr-
  namespace: tekton-pipelines
spec:
  taskRef:
    name: deploy-using-kubectl
  resources:
    - name: git-source
      resourceRef:
        name: demo-app-git
  params:
    - name: pathToYamlFile
      value: "manifests/demo-api.yml"
    - name: imageUrl
      value: "nginx"
    - name: imageTag
      value: "alpine"
  serviceAccountName: pipeline-account